[cerebrium.deployment]
name = "eth-predictor"
python_version = "3.12"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.runtime.custom]
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
port = 8080
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 1
memory = 2.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 10

[cerebrium.dependencies.pip]
numpy = "==1.26.0"
optuna = "==3.3.0"
pyarrow = "==19.0.1"
setuptools = "==78.1.0"
python-dotenv = "==1.1.0"
xgboost = "==3.0.0"
pandas = "==2.2.3"
comet-ml = "==3.49.7"
scikit-learn = "==1.6.1"
fire = "==0.7.0"
fastapi = "==0.115.12"
uvicorn = "==0.34.0"